# Generated by Django 5.1.1 on 2024-09-24 17:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Administracion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_comercial', models.CharField(max_length=100)),
                ('numero_receptor', models.CharField(max_length=5, unique=True)),
                ('direccion', models.CharField(max_length=255)),
                ('provincia', models.CharField(choices=[('ALAVA', 'ALAVA/ARABA'), ('ALBACETE', 'ALBACETE'), ('ALICANTE', 'ALICANTE/ALACANT'), ('ALMERIA', 'ALMERIA'), ('ASTURIAS', 'ASTURIAS'), ('AVILA', 'AVILA'), ('BADAJOZ', 'BADAJOZ'), ('BALEARES', 'BALEARES'), ('BARCELONA', 'BARCELONA'), ('VIZCAYA', 'BIZKAIA/VIZCAYA'), ('BURGOS', 'BURGOS'), ('CACERES', 'CACERES'), ('CADIZ', 'CADIZ'), ('CANTABRIA', 'CANTABRIA'), ('CASTELLON', 'CASTELLON/CASTELLÓ'), ('CEUTA', 'CEUTA'), ('CIUDAD_REAL', 'CIUDAD REAL'), ('CORDOBA', 'CORDOBA'), ('CORUÑA', 'CORUÑA (A)'), ('CUENCA', 'CUENCA'), ('GUIPUZCOA', 'GIPUZKOA'), ('GIRONA', 'GIRONA'), ('GRANADA', 'GRANADA'), ('GUADALAJARA', 'GUADALAJARA'), ('HUELVA', 'HUELVA'), ('HUESCA', 'HUESCA'), ('JAEN', 'JAEN'), ('LEON', 'LEON'), ('LLEIDA', 'LLEIDA'), ('LUGO', 'LUGO'), ('MADRID', 'MADRID'), ('MALAGA', 'MALAGA'), ('MELILLA', 'MELILLA'), ('MURCIA', 'MURCIA'), ('NAVARRA', 'NAVARRA'), ('OURENSE', 'OURENSE'), ('PALENCIA', 'PALENCIA'), ('LAS_PALMAS', 'LAS PALMAS '), ('PONTEVEDRA', 'PONTEVEDRA'), ('LA_RIOJA', 'LA RIOJA'), ('SALAMANCA', 'SALAMANCA'), ('SEGOVIA', 'SEGOVIA'), ('SEVILLA', 'SEVILLA'), ('SORIA', 'SORIA'), ('SANTA_CRUZ_DE_TENERIFE', 'SANTA CRUZ DE TENERIFE'), ('TARRAGONA', 'TARRAGONA'), ('TERUEL', 'TERUEL'), ('TOLEDO', 'TOLEDO'), ('VALENCIA', 'VALENCIA/VALÈNCIA'), ('VALLADOLID', 'VALLADOLID'), ('ZAMORA', 'ZAMORA'), ('ZARAGOZA', 'ZARAGOZA')], max_length=100)),
                ('localidad', models.CharField(max_length=100)),
                ('numero_administracion', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('PF', 'Persona Fisica'), ('PJ', 'Persona Juridica')], default='PF', max_length=2)),
                ('dni', models.CharField(max_length=9, unique=True)),
                ('nombre', models.CharField(max_length=50)),
                ('apellidos', models.CharField(blank=True, max_length=50, null=True)),
                ('telefono', models.CharField(max_length=12)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('id_administracion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='propietario', to='usuario.administracion')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
