# Generated by Django 5.1.1 on 2024-10-03 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administracion',
            name='provincia',
            field=models.CharField(choices=[('ALAVA/ARABA', 'ALAVA'), ('ALBACETE', 'ALBACETE'), ('ALICANTE/ALACANT', 'ALICANTE'), ('ALMERIA', 'ALMERIA'), ('ASTURIAS', 'ASTURIAS'), ('AVILA', 'AVILA'), ('BADAJOZ', 'BADAJOZ'), ('BALEARES', 'BALEARES'), ('BARCELONA', 'BARCELONA'), ('BIZKAIA/VIZCAYA', 'VIZCAYA'), ('BURGOS', 'BURGOS'), ('CACERES', 'CACERES'), ('CADIZ', 'CADIZ'), ('CANTABRIA', 'CANTABRIA'), ('CASTELLON/CASTELLÓ', 'CASTELLON'), ('CEUTA', 'CEUTA'), ('CIUDAD REAL', 'CIUDAD_REAL'), ('CORDOBA', 'CORDOBA'), ('CORUÑA (A)', 'CORUÑA'), ('CUENCA', 'CUENCA'), ('GIPUZKOA', 'GUIPUZCOA'), ('GIRONA', 'GIRONA'), ('GRANADA', 'GRANADA'), ('GUADALAJARA', 'GUADALAJARA'), ('HUELVA', 'HUELVA'), ('HUESCA', 'HUESCA'), ('JAEN', 'JAEN'), ('LEON', 'LEON'), ('LLEIDA', 'LLEIDA'), ('LUGO', 'LUGO'), ('MADRID', 'MADRID'), ('MALAGA', 'MALAGA'), ('MELILLA', 'MELILLA'), ('MURCIA', 'MURCIA'), ('NAVARRA', 'NAVARRA'), ('OURENSE', 'OURENSE'), ('PALENCIA', 'PALENCIA'), ('LAS PALMAS', 'LAS_PALMAS'), ('PONTEVEDRA', 'PONTEVEDRA'), ('LA RIOJA', 'LA_RIOJA'), ('SALAMANCA', 'SALAMANCA'), ('SEGOVIA', 'SEGOVIA'), ('SEVILLA', 'SEVILLA'), ('SORIA', 'SORIA'), ('SANTA CRUZ DE TENERIFE', 'SANTA_CRUZ_DE_TENERIFE'), ('TARRAGONA', 'TARRAGONA'), ('TERUEL', 'TERUEL'), ('TOLEDO', 'TOLEDO'), ('VALENCIA/VALÈNCIA', 'VALENCIA'), ('VALLADOLID', 'VALLADOLID'), ('ZAMORA', 'ZAMORA'), ('ZARAGOZA', 'ZARAGOZA')], max_length=100),
        ),
    ]
