# Generated by Django 5.1.1 on 2024-10-03 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_alter_administracion_provincia'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='id_administracion',
            new_name='administracion',
        ),
    ]
