# Generated by Django 5.1.1 on 2024-10-01 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuario', '0005_alter_administracion_provincia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.IntegerField(choices=[(0, 'ENVIAR'), (1, 'RECIBIR')])),
                ('numero', models.CharField(max_length=5)),
                ('num_series', models.CharField(max_length=3)),
                ('sorteo', models.CharField(max_length=3)),
                ('condicion', models.IntegerField(choices=[(0, 'CESION'), (1, 'INDIFERENTE'), (2, 'EXPLICITA')])),
                ('num_cond', models.CharField(max_length=5)),
                ('num_series_cond', models.CharField(max_length=3)),
                ('sorteo_cond', models.CharField(max_length=3)),
                ('estado', models.IntegerField(choices=[(0, 'PENDIENTE'), (1, 'COMPLETADA'), (2, 'CANCELADA')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('administracion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes', to='usuario.administracion')),
            ],
        ),
        migrations.CreateModel(
            name='SolicitudRespuesta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('numero', models.CharField(max_length=5)),
                ('num_series', models.CharField(max_length=3)),
                ('sorteo', models.CharField(max_length=3)),
                ('estado', models.IntegerField(choices=[(0, 'PENDIENTE'), (1, 'COMPLETADA'), (2, 'CANCELADA'), (3, 'ACEPTADA'), (4, 'RECHAZADA')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('administracion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='usuario.administracion')),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='intercambios.solicitud')),
            ],
        ),
        migrations.CreateModel(
            name='Intercambio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('numeros_adm1', models.JSONField()),
                ('numeros_adm2', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('administracion1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intercambios_enviados', to='usuario.administracion')),
                ('administracion2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intercambios_recibidos', to='usuario.administracion')),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intercambios', to='intercambios.solicitud')),
                ('solicitud_respuesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intercambios', to='intercambios.solicitudrespuesta')),
            ],
        ),
    ]
