# Generated by Django 5.1.1 on 2024-10-08 07:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('usuario', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoteriaIntercambio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=5)),
                ('num_series', models.IntegerField()),
                ('administracion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.administracion')),
                ('sorteo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loteria_intercambio', to='core.sorteo')),
            ],
        ),
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.IntegerField(choices=[(0, 'ENVIAR'), (1, 'RECIBIR')])),
                ('numero', models.CharField(max_length=5)),
                ('num_series', models.IntegerField()),
                ('condicion', models.IntegerField(choices=[(0, 'CESION'), (1, 'INDIFERENTE'), (2, 'EXPLICITA')])),
                ('num_cond', models.CharField(blank=True, max_length=5, null=True)),
                ('num_series_cond', models.IntegerField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('ABIERTA', 'Abierta'), ('COMPLETADA', 'Completada'), ('CANCELADA', 'Cancelada')], default='ABIERTA', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('administracion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes', to='usuario.administracion')),
                ('sorteo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes', to='core.sorteo')),
                ('sorteo_cond', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_cond', to='core.sorteo')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Respuesta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('numero', models.CharField(max_length=5)),
                ('num_series', models.IntegerField()),
                ('estado', models.CharField(choices=[('ABIERTA', 'Abierta'), ('ACEPTADA', 'Aceptada'), ('COMPLETADA', 'Completada'), ('RECHAZADA', 'Rechazada'), ('CANCELADA', 'Cancelada')], default='ABIERTA', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('administracion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='usuario.administracion')),
                ('sorteo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='core.sorteo')),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='intercambios.solicitud')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Intercambio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recibidas_en_intercambio', to='intercambios.loteriaintercambio')),
                ('origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enviadas_en_intercambio', to='intercambios.loteriaintercambio')),
                ('solicitud_respuesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intercambios', to='intercambios.respuesta')),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intercambios', to='intercambios.solicitud')),
            ],
        ),
    ]
