# Generated by Django 5.1.1 on 2024-10-03 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('intercambios', '0001_initial'),
        ('usuario', '0003_rename_id_administracion_usuario_administracion'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SolicitudRespuesta',
            new_name='Respuesta',
        ),
    ]
