repos:
  # general checks (see here: https://pre-commit.com/hooks.html)
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-yaml
        args: ["--allow-multiple-documents"]
        files: ^server/
      - id: end-of-file-fixer
        files: ^server/
      - id: trailing-whitespace
        files: ^server/
      - id: check-added-large-files
        files: ^server/
      - id: check-json
        files: ^server/

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.8  # Use the latest stable version of ruff
    hooks:
      # Run the linter.
      - id: ruff
        args: ["--fix"]
        files: ^server/

  - repo: local
    hooks:
      - id: django-check
        name: Django Check
        entry: python
        language: system
        pass_filenames: false
        args: [server/manage.py, check]

