# Generated by Django 5.1.1 on 2024-09-16 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0004_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propietario',
            name='tipo_propietarario',
        ),
        migrations.AddField(
            model_name='propietario',
            name='tipo_propietario',
            field=models.CharField(choices=[('PF', 'Persona Fisica'), ('PJ', 'Persona Juridica')], default='PF', max_length=25),
        ),
    ]
