# Generated by Django 5.1.1 on 2024-09-19 21:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0005_remove_propietario_tipo_propietarario_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='administracion',
            name='propietario',
        ),
        migrations.RemoveField(
            model_name='administracion',
            name='email',
        ),
        migrations.RemoveField(
            model_name='administracion',
            name='telefono',
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('dni', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=50)),
                ('tipo', models.CharField(choices=[('PF', 'Persona Fisica'), ('PJ', 'Persona Juridica')], default='PF', max_length=25)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefono', models.CharField(max_length=12)),
                ('id_administracion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='administracion',
            name='id_propietario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='administracion.usuario'),
        ),
        migrations.DeleteModel(
            name='Propietario',
        ),
    ]
