
TIPOS_SOLICITUD = [(0, 'ENVIAR'), (1, 'RECIBIR')]

TIPOS_CONDICION = [(0, 'CESION'), (1, 'INDIFERENTE'), (2, 'EXPLICITA')]

ESTADO_SOLICITUD = [(0, 'ABIERTA'), (1, 'COMPLETADA'), (2, 'CANCELADA')] 

ESTADO_RESPUESTA = [(0, 'ABIERTA'), (1, 'COMPLETADA'), (2, 'CANCELADA')]
