TIPOS_PERSONA = [("PF", "Persona Fisica"), ("PJ", "Persona Juridica")]

PROVINCIAS = {
    # "-- ANDORRA -- ": "ANDORRA",
    "ALAVA/ARABA": "ALAVA",
    "ALBACETE": "ALBACETE",
    "ALICANTE/ALACANT": "ALICANTE",
    "ALMERIA": "ALMERIA",
    "ASTURIAS": "ASTURIAS",
    "AVILA": "AVILA",
    "BADAJOZ": "BADAJOZ",
    "BALEARES": "BALEARES",
    "BARCELONA": "BARCELONA",
    "BIZKAIA/VIZCAYA": "VIZCAYA",
    "BURGOS": "BURGOS",
    "CACERES": "CACERES",
    "CADIZ": "CADIZ",
    "CANTABRIA": "CANTABRIA",
    "CASTELLON/CASTELLÓ": "CASTELLON",
    "CEUTA": "CEUTA",
    "CIUDAD REAL": "CIUDAD_REAL",
    "CORDOBA": "CORDOBA",
    "CORUÑA (A)": "CORUÑA",
    "CUENCA": "CUENCA",
    "GIPUZKOA": "GUIPUZCOA",
    "GIRONA": "GIRONA",
    "GRANADA": "GRANADA",
    "GUADALAJARA": "GUADALAJARA",
    "HUELVA": "HUELVA",
    "HUESCA": "HUESCA",
    "JAEN": "JAEN",
    "LEON": "LEON",
    "LLEIDA": "LLEIDA",
    "LUGO": "LUGO",
    "MADRID": "MADRID",
    "MALAGA": "MALAGA",
    "MELILLA": "MELILLA",
    "MURCIA": "MURCIA",
    "NAVARRA": "NAVARRA",
    "OURENSE": "OURENSE",
    "PALENCIA": "PALENCIA",
    "LAS PALMAS": "LAS_PALMAS",
    "PONTEVEDRA": "PONTEVEDRA",
    "LA RIOJA": "LA_RIOJA",
    "SALAMANCA": "SALAMANCA",
    "SEGOVIA": "SEGOVIA",
    "SEVILLA": "SEVILLA",
    "SORIA": "SORIA",
    "SANTA CRUZ DE TENERIFE": "SANTA_CRUZ_DE_TENERIFE",
    "TARRAGONA": "TARRAGONA",
    "TERUEL": "TERUEL",
    "TOLEDO": "TOLEDO",
    "VALENCIA/VALÈNCIA": "VALENCIA",
    "VALLADOLID": "VALLADOLID",
    "ZAMORA": "ZAMORA",
    "ZARAGOZA": "ZARAGOZA",
}

PROVINCIAS_CHOICES = [(key, value) for key, value in PROVINCIAS.items()]

# from core.models import Provincia

# def get_province_choices_by_country(country):
#     provinces = Provincia.objects.filter(pais=country).values_list('id', 'nombre')
#     return list(provinces)
