# Generated by Django 5.1.1 on 2024-09-17 22:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Boleto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('numero_boleto', models.IntegerField()),
                ('series_boleto', models.JSONField()),
                ('num_series_disponibles', models.IntegerField()),
                ('administracion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
